### ISSUE TITLE
Default deactivate `;` binding does not work on QWERTZ keyboard layout

### ISSUE THREAD

**Issue by Kissaki** [wirekang/mouseable#1]
The QWERTZ (German) keyboard layout has no dedicated/default `;` key. `;` is entered with SHIFT+`,`.

Using SHIFT+, does not work to deactivate.

**Comment by Kissaki** [comment]
It looks like the displayed key is always of a US keyboard layout.

So `ö` shows as ```, and `ä` shows as `'` for example.

**Comment by Kissaki** [comment]
What is displayed as `;` is the `ü` key for me. So it doesn’t seem to be a direct mapping between the US and DE keyboard layouts/keys either?

* https://en.wikipedia.org/wiki/QWERTY#English
* https://en.wikipedia.org/wiki/QWERTZ#Austria_and_Germany

**Comment by wirekang** [comment]
First of all, I apologize for not thinking about anything other than QWERTY. Although I didn't know the exact cause, I'll solve it as soon as possible.

**Comment by Kissaki** [comment]
No worries :)

**Comment by j-ilden** [comment]
I would like to suggest that the config file or input be UTF-8. That can solve a lot of problems later as well.
