### ISSUE TITLE
2.0 acceleration carries over when keys are changed

### ISSUE THREAD

**Issue by abrudz** [wirekang/mouseable#17]
If I hold down the key for moving right, but overshoot my target, I'd immediately switch to the move left key, but the acceleration continues, causing my mouse to fly left at way too high speed.

**Comment by wirekang** [comment]
It's intented behavior. You can prevent it by releasing the keys( even a very short time).

**Comment by wirekang** [comment]
It was intented behavior, but I will fix it.

**Comment by wirekang** [comment]
Fixed.
