### ISSUE TITLE
Adjust horizontal and vertical teleport distances independently

### ISSUE THREAD

**Issue by jbcormoreche** [wirekang/mouseable#19]
At the moment, there is only one field that applies the same number to both the horizontal and the vertical teleport distance (unless I am missing something).
Depending on each monitor and monitor setup (ultrawide, vertical monitor, multiple monitors), the distance to travel horizontally and vertically is different and the jumps don't have the same impact.
So it would be nice to have two fields to adjust them independently.

**Comment by wirekang** [comment]
I'm little confused. You mean **TeleportDistanceH/V** in previous version?

**Comment by jbcormoreche** [comment]
I don't remember how it was in the previous version as I didn't use it at the time but yes this is what I mean.
How do I set TeleportDistanceH/V in the new version?
