### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by SomeRandomDude870** [wirekang/mouseable#23]
Hi,
the Portable Version does not work. It throws three "windows Typeerror" and the below the  Hotkey Example is blank.

I now installed the Installer and.... well I have no idea how to use it.
It shows the commands and their corresponding Keys, but it does do nothing.

Like I click "alt+j" and then "s, w, d" etc and nothing moves.

What else do I have to do?

**Comment by wirekang** [comment]
There seems to be a problem. What version of windows and chrome(edge) are you running?

**Comment by wirekang** [comment]
Close issue due to lack of information.
