### ISSUE TITLE
cannot use mouseable while focusing a RDP window

### ISSUE THREAD

**Issue by iamtend0** [wirekang/mouseable#25]
mouseable doesn't work when I'm focusing a RDP window. That's pitty, as I really like the software... ☹

**Comment by wirekang** [comment]
Have you tried running as administrator? And alternatively, you can install Mouseable in RDP host computer. This is the method I use often.

**Comment by iamtend0** [comment]
Hey, yes I've tried. It works for the task manager but not for controlling the machine with RDP.
I thought about that, I'll test and give a feedback! Thank you
